name: foodie
version: 1.0.0+1
publish_to: none
description: A  Flutter project For Machine Test
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  dio: ^5.4.3+1
  pinput: ^3.0.1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "asset/foodie-icon.jpg"
  min_sdk_android: 21

flutter: 
  uses-material-design: true
  assets:
    - asset/svg/
    - asset/png/
    - asset/foodie-icon.jpg

